[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://backend-kvpfwl36m-hargun-singhs-projects-122b6573.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 